### ISSUE TITLE
Issue and Pull Request Templates for Enhanced Collaboration

### ISSUE THREAD

**Issue by UTSAVS26** [vespperhq/vespper#34]
### Description:
As a participant in Hacktoberfest, I am excited to improve the collaboration process in our repository by adding structured issue and pull request templates. These templates will help contributors clearly communicate their ideas, report bugs, or propose new features, ensuring that all necessary information is provided for effective review and resolution.

#### Key Features:
- **Issue Template**: This will guide users in reporting bugs or suggesting enhancements, prompting them to include essential details like steps to reproduce, expected vs. actual behavior, and any relevant screenshots.
  
- **Pull Request Template**: This template will streamline the process for contributors submitting code changes, encouraging them to describe their modifications, reference related issues, and outline any necessary context for reviewers.

By implementing these templates, we aim to foster a more organized and efficient development workflow, making it easier for all contributors to participate and collaborate effectively.

**Comment by david1542** [comment]
Hi @UTSAVS26! Thanks for filing this issue. I've added 2 templates for issues - bug fixes and feature requests.

As for PR templates - I think we're too early for this. We want to encourage contribution as much as possible and lower the friction for contributors.

Thanks a lot for your inputs!

**Comment by UTSAVS26** [comment]
Hi @david1542 ,

Thank you for your update and for adding the issue templates for bug fixes and feature requests – that's great!

**Comment by UTSAVS26** [comment]
I noticed a few areas in the README file that could be improved for better clarity. Would it be alright if I contribute by updating it? I think it could enhance the onboarding experience for new contributors.

**Comment by david1542** [comment]
@UTSAVS26 Yeah, got for it! Feel free to open a PR :)
