### ISSUE TITLE
Add 3D Pop-Up Effect with Perspective on Hover

### ISSUE THREAD

**Issue by ayushsingh199** [vespperhq/vespper#36]
### **Is your feature request related to a problem? Please describe.**
I'm always frustrated when elements on the page feel too static and don't have enough visual engagement. A pop-up effect that uses perspective when elements are hovered would add more depth and interactivity to the page, making it more visually appealing and dynamic.

### **Describe the solution you'd like**
I would like to see a 3D pop-up effect using CSS perspective applied to certain elements (e.g., cards, buttons, images). When a user hovers over these elements, they should appear to lift off the page slightly, creating a 3D effect as if they are popping out towards the user. This can be achieved using CSS `transform`, `perspective`, and `transition` properties for smooth animation.

### **Describe alternatives you've considered**
An alternative could be using simpler hover effects like scaling the element slightly or adding a shadow, but these don't provide the same depth and immersive experience as a perspective-based pop-up effect. Another option is to use JavaScript libraries, but a pure CSS solution would be preferable for performance and simplicity.
<img width="1264" alt="Screenshot 2024-10-16 at 12 02 42 AM" src="https://github.com/user-attachments/assets/2e6db7aa-d978-4d51-8ac6-011d37e2c770">

**Comment by sairiteshdomakuntla** [comment]
hello @ayushsingh199 , i would like to contribute to this, can you assign this to me?

**Comment by topaztee** [comment]
Hey thanks! our website is actually on webflow not this repo. But thanks for the suggestion!
